const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs/promises')
const os = require('node:os')
const path = require('node:path')
const { createLibraryStore } = require('../src/library-store')

test('lagrar filer beständigt, deduplicerar och tar bort dem', async t => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), 'sjomatning-library-'))
  t.after(() => fs.rm(root, { recursive: true, force: true }))
  const store = createLibraryStore(root)
  const bytes = Buffer.from('mätdata')
  await store.persist([{ name: 'ett.txt', bytes }, { name: 'kopia.txt', bytes }])
  let files = await store.list()
  assert.equal(files.length, 1)
  assert.equal(files[0].name, 'ett.txt')
  assert.deepEqual(files[0].bytes, bytes)
  assert.equal(await store.remove(files[0].id), true)
  files = await store.list()
  assert.equal(files.length, 0)
})

test('namn och samtidiga redigeringar överlever omstart utan att original ändras', async t => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), 'sjomatning-edit-'))
  t.after(() => fs.rm(root, { recursive: true, force: true }))
  const store = createLibraryStore(root)
  const bytes = Buffer.from('2026-09-13,12:00:00,58.5,15.6,3,4')
  await store.persist([{ name: 'original.csv', bytes }])
  const [{ id }] = await store.list()
  const edits = { points: [{ lat: 58.6, lon: 15.6, depth: 2 }], depthAdjustment: .5 }
  await Promise.all([store.update(id, { edits }), store.update(id, { name: 'Åäö båt' })])
  const reopened = createLibraryStore(root)
  let [file] = await reopened.list()
  assert.equal(file.name, 'Åäö båt.csv')
  assert.deepEqual(file.edits, edits)
  assert.deepEqual(file.bytes, bytes)
  await reopened.update(id, { edits: null })
  ;[file] = await reopened.list()
  assert.equal(file.edits, null)
  assert.deepEqual(file.bytes, bytes)
  await assert.rejects(reopened.update(id, { name: '../escape.csv' }))
})

test('manuscript annotations survive restart, editing and deletion without modifying the PDF',async t=>{
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'sjomatning-notes-'))
 t.after(()=>fs.rm(root,{recursive:true,force:true}))
 const store=createLibraryStore(root),bytes=Buffer.from('original manuscript')
 await store.persist([{name:'manus.pdf',bytes}]);const [{id}]=await store.list()
 const note={id:'note',page:1,x:.25,y:.5,text:'4,2 Åäö',size:12,color:'#c62828'}
 await store.update(id,{annotations:[note]})
 const reopened=createLibraryStore(root)
 let [file]=await reopened.list();assert.deepEqual(file.annotations,[note]);assert.deepEqual(file.bytes,bytes)
 await reopened.update(id,{annotations:[{...note,text:'5,1'}]});[file]=await reopened.list();assert.equal(file.annotations[0].text,'5,1')
 await reopened.update(id,{annotations:[]});[file]=await reopened.list();assert.deepEqual(file.annotations,[]);assert.deepEqual(file.bytes,bytes)
})
