const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs/promises')
const os = require('node:os')
const path = require('node:path')
const { createLibraryStore } = require('../src/library-store')

test('lagrar filer beständigt, deduplicerar och tar bort dem', async t => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), 'sjomatning-library-'))
  t.after(() => fs.rm(root, { recursive: true, force: true }))
  const store = createLibraryStore(root)
  const bytes = Buffer.from('mätdata')
  await store.persist([{ name: 'ett.txt', bytes }, { name: 'kopia.txt', bytes }])
  let files = await store.list()
  assert.equal(files.length, 1)
  assert.equal(files[0].name, 'ett.txt')
  assert.deepEqual(files[0].bytes, bytes)
  assert.equal(await store.remove(files[0].id), true)
  files = await store.list()
  assert.equal(files.length, 0)
})
