CREATE TABLE files (id TEXT PRIMARY KEY, name TEXT NOT NULL, extension TEXT NOT NULL, size INTEGER NOT NULL, addedAt TEXT NOT NULL, metadata TEXT NOT NULL DEFAULT '{}');
CREATE TABLE settings (key TEXT PRIMARY KEY, value TEXT NOT NULL);
ALTER TABLE files ADD COLUMN owner TEXT NOT NULL DEFAULT 'admin';
CREATE TABLE users (id TEXT PRIMARY KEY, name TEXT NOT NULL, role TEXT NOT NULL CHECK(role IN ('all','own')), tokenHash TEXT NOT NULL UNIQUE, active INTEGER NOT NULL DEFAULT 1);
