import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
const origin = process.argv[2];
if (origin !== 'https://sjomatning-web.led-karlsson.workers.dev') throw new Error('Ange projektets driftsatta adress.');
const root = await fetch(origin); assert.equal(root.status,200); assert.match(await root.text(),/Sjömätning/);
assert.equal((await fetch(origin+'/api/files')).status,401);
const password=(await readFile('web/admin-access.txt','utf8')).trim();
const login=await fetch(origin+'/api/login',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify({password})});
assert.equal(login.status,200);
const cookie=login.headers.get('set-cookie').split(';')[0];
const session=await (await fetch(origin+'/api/session',{headers:{Cookie:cookie}})).json(); assert.equal(session.id,'admin');
const files=await fetch(origin+'/api/files',{headers:{Cookie:cookie}}); assert.equal(files.status,200);
const users=await fetch(origin+'/api/users',{headers:{Cookie:cookie}}); assert.equal(users.status,200);
console.log(JSON.stringify({site:origin,login:'OK',unauthenticatedAccess:'blocked',library:'OK',users:'OK',storageReady:session.storageReady}));
