import {importObs,obsGroups,exportObs} from './obs-format.mjs';
export function mountObsTools(host,api,refresh){
 const add=document.createElement('button'),save=document.createElement('button'),status=document.createElement('p');add.textContent='Importera OBS';save.textContent='Exportera OBS';host.append(add,save,status);
 add.onclick=()=>{const input=document.createElement('input');input.type='file';input.accept='.obs';input.multiple=true;input.onchange=async()=>{add.disabled=save.disabled=true;let count=0,skipped=0;try{
  const events=[];for(const file of input.files)events.push(...await importObs(await file.text(),file.name));
  const known=new Set((await api.journalList()).rows.map(r=>r.event.id));
  for(const event of events){if(known.has(event.id)){skipped++;continue;}await api.journalSave({event,expectedMutation:null,baseRevision:0,deleted:false});known.add(event.id);count++;status.textContent=`${count} observationer importerade…`;}
  status.textContent=`${count} observationer importerade. ${skipped} redan importerade hoppades över.`;
 }catch(error){status.textContent=`${count} observationer sparade. Importen stoppades: ${error.message}`;}finally{try{await refresh();}catch(error){status.textContent+=` Kunde inte uppdatera listan: ${error.message}`;}finally{add.disabled=save.disabled=false;}}};input.click();};
 save.onclick=async()=>{try{const groups=obsGroups((await api.journalList()).rows);if(!groups.length)throw new Error('Det finns inga sparade händelser med mätpass.');const dialog=document.createElement('dialog');dialog.className='journal-dialog';dialog.innerHTML='<form><h2>Exportera Jonas OBS</h2><label>Mätpass och datum<select></select></label><p>En fil per mätpass och datum. Referens 33,00 m RH00 krävs.</p><p role="status"></p><button type="submit">Exportera</button> <button type="button">Avbryt</button></form>';const select=dialog.querySelector('select');for(const group of groups){const option=document.createElement('option');option.value=group.key;option.textContent=group.name;select.append(option);}document.body.append(dialog);dialog.showModal();dialog.onclose=()=>dialog.remove();dialog.querySelector('[type=button]').onclick=()=>dialog.close();dialog.querySelector('form').onsubmit=async e=>{e.preventDefault();const button=dialog.querySelector('[type=submit]');button.disabled=true;try{const group=groups.find(g=>g.key===select.value);await api.exportObsFile({name:'observationer-'+group.events[0].occurredAt.slice(0,10)+'.obs',content:exportObs(group.events)});dialog.close();}catch(error){dialog.querySelector('[role=status]').textContent=error.message;}finally{button.disabled=false;}};}catch(error){status.textContent=error.message;}};
}
