const { contextBridge, ipcRenderer, webUtils } = require('electron')

contextBridge.exposeInMainWorld('sjomatning', {
  journalList: () => ipcRenderer.invoke('journal:list'),
  journalSave: value => ipcRenderer.invoke('journal:save', value),
  journalResolve: (id,choice) => ipcRenderer.invoke('journal:resolve',id,choice),
  journalSync: options => ipcRenderer.invoke('journal:sync',options),
  journalExport: format => ipcRenderer.invoke('journal:export',format),
  updateLibraryFile: (id, changes) => ipcRenderer.invoke('library:update', id, changes),
  openLibrary: () => ipcRenderer.invoke('files:open-library'),
  openPdf: () => ipcRenderer.invoke('files:open-pdf'),
  openLogs: () => ipcRenderer.invoke('files:open-logs'),
  openFolder: () => ipcRenderer.invoke('files:open-folder'),
  scanDroppedEntries: files => ipcRenderer.invoke('files:scan-paths', files.map(file => webUtils.getPathForFile(file))),
  listLibrary: () => ipcRenderer.invoke('library:list'),
  listCloudUsers: options => ipcRenderer.invoke('library:cloud-users', options),
  syncCloudLibrary: options => ipcRenderer.invoke('library:sync-cloud', options),
  onCloudSyncProgress: callback => ipcRenderer.on('library:sync-progress', (_event, data) => callback(data)),
  removeLibraryFile: id => ipcRenderer.invoke('library:remove', id),
  launchPdf: () => ipcRenderer.invoke('files:launch-pdf'),
  getRoxenWaterLevel: date => ipcRenderer.invoke('roxen:water-level', date),
  getAppInfo: () => ipcRenderer.invoke('app:info'),
  exportManuscriptPdf: id => ipcRenderer.invoke('manuscript:export-pdf', id),
  createTrackPoint: value => ipcRenderer.invoke('tracks:create-point',value),
  exportTracks: options => ipcRenderer.invoke('tracks:export', options),
  startLiveSession: metadata => ipcRenderer.invoke('live:start', metadata),
  appendLiveData: data => ipcRenderer.invoke('live:append', data),
  stopLiveSession: id => ipcRenderer.invoke('live:stop', id),
  onUpdaterStatus: callback => ipcRenderer.on('updater:status', (_event, status) => callback(status)),
  installUpdate: () => ipcRenderer.invoke('updater:install')
})
